### ISSUE TITLE
Issue upgrading to version 3.7.7

### ISSUE THREAD

**Issue by robbo10** [pivotal-cf/cf-rabbitmq-release#112]
Hello, 

We have deployed version `252.0.0` however after the upgrade we are still seeing the version set as `3.6.16`, we were expecting to see `3.7.7`.

Is there something we have missed here?

Thanks.

**Comment by robbo10** [comment]
Seems that this could be similar to the following closed issue #72 ?

Was there a workaround implemented for this?

**Comment by robbo10** [comment]
This issue can be closed!

We created an ops file to override the default version :)

**Comment by mkuratczyk** [comment]
Hey. Do you mean an ops-file to modify the template/sample manifest provided in https://github.com/pivotal-cf/cf-rabbitmq-release/blob/master/manifests/cf-rabbitmq-template.yml?

If so I guess it's time to update that default indeed. We'll think through potential consequences (we don't want users upgrading accidentally).

**Comment by robbo10** [comment]
Hey @mkuratczyk thats correct, this was how we got around the issue.  We could PR the readme for how to upgrade so that it is clear for other users.  That way it also ensures folk dont upgrade accidentally as the default is still 3.6.

**Comment by mkuratczyk** [comment]
Thanks. We'll discuss that within the team - on one hand an ops-file prevents accidental upgrades, on the other hand we want people to have the latest and greatest (and maintained...) versions deployed by default. I'll leave this issue open as a reminder for now.

**Comment by benjamintillett** [comment]
Hey @robbo10 we have finally chatted with the team and agree that the release should use v3.7.x rather than 3.6.x by default. You can expect this change in an upcoming release!

**Comment by ferozjilla** [comment]
v253.0.0 changes the default to 3.7.
