### ISSUE TITLE
Forward logs from HA proxy and broker nodes

### ISSUE THREAD

**Issue by mrdavidlaing** [pivotal-cf/cf-rabbitmq-release#12]
It appears that only the `rabbitmq-server` job that can be configured to forward its logs via syslog. (see [spec](https://github.com/pivotal-cf/cf-rabbitmq-release/blob/master/jobs/rabbitmq-server/spec#L41) and [rsyslog config](https://github.com/pivotal-cf/cf-rabbitmq-release/blob/master/jobs/rabbitmq-server/templates/syslog_forwarder.conf.erb))

As far as I can tell you cannot configure the `rabbitmq-haproxy` ( [spec](https://github.com/pivotal-cf/cf-rabbitmq-release/blob/master/jobs/rabbitmq-haproxy/spec) ) or `rabbitmq-broker` ( [spec](https://github.com/pivotal-cf/cf-rabbitmq-release/blob/master/jobs/rabbitmq-broker/spec) ) jobs to forward their logs.

Is this correct?

If so, is this an intentional omission, or just a missing "feature" ?

Thanks!

**Comment by benlaplanche** [comment]
Hi David,

This is a missing feature at the moment, we prioritised emitting logs from the RabbitMQ nodes themselves.

Feel free to submit a PR if you would like this functionality.

Cheers
Ben
