### ISSUE TITLE
Allow to create multiple broker users

### ISSUE THREAD

**Issue by maryoush** [pivotal-cf/cf-rabbitmq-release#14]
Hi,
please see details : 
http://stackoverflow.com/questions/32783762/how-to-provide-more-broker-users-in-bosh-release-rabbitmq

Regards M.

**Comment by benlaplanche** [comment]
@maryoush can you please expand upon what you are looking to achieve through having more users? This isn't something we currently support or have a need for.

**Comment by maryoush** [comment]
Hi
the main use case is to monitor potential performance issues with channels
(to reuse them or create always new). We have this kind of concerns in the
sender and receiver - we are using rabbit as kid of point 2 point queue.
Having different users for broker would allow us to easily determine
whether we have issue on sender or receiver side.

Regards M.

W dniu piątek, 25 września 2015 Ben Laplanche <notifications@github.com>
napisał(a):

**Comment by michaelklishin** [comment]
So the goal is to have a user per "role", not per app. That's not unreasonable but doesn't quite fit CF's world view.

**Comment by benlaplanche** [comment]
When you say broker i'm assuming you mean RabbitMQ Node. 

When you create an instance of the RabbitMQ service using $cf create-service it creates a vHost on the RabbitMQ cluster. When you bind to this instance you get admin credentials to that vHost where you can monitor the publishers / consumers for that instance.

You can also use the $cf create-service-key command to get credentials,

So i suggest you create different bindings or service keys to try and differentiate. 

I suggest you use this approach so i'm going to close the issue and log a feature request in my product backlog.

**Comment by maryoush** [comment]
Actually the topology looks like this.
 There is HA node rabbit mq proxy backed by few rabbit mq broker instances. 
On the sender side there is 1-n (fixed number )nodes publishing on one queue (no exchange) and there might 1 or more (fixed number )consumers - we don't care which instance consume - they all should be of the same functionality. 
We would like to be able to diagnose on broker (or rather HA proxy side ) on which side (and which) node we are keeping broker resources eg channel, connection. 
We would like to create/ prepare the deployment with predefined setup so we would like to distinguish the particular instances interacting - using users was the first idea. 
We would like to avoid dynamic interaction via cf api with application on the runtime.
