### ISSUE TITLE
Ensure the management_domain gets registered as a CF route

### ISSUE THREAD

**Issue by geofffranks** [pivotal-cf/cf-rabbitmq-release#15]
Currently you can customize the management_domain (used in the Dashboard URL advertised to CF services). However, the route-registrar process on the rabbitmq-broker job does not advertise that domain in a route. Instead it advertises `pivotal-rabbitmq.<system-domain>`.  These values should probably be synchronized.

**Comment by geofffranks** [comment]
Was this fixed?

**Comment by dlresende** [comment]
For some reason Tracker didn't synchronise with Github for this issue...

The issue has been closed with the following comment:
_Issue no longer makes sense as the way route registration is handled has changed over time._

The multi-tenant broker has been split out of the cf-rabbitmq release and will be soon publicly available again (#59).

**Comment by geofffranks** [comment]
Cool, thanks!
