### ISSUE TITLE
Unable to configure rabbit to use two way tls

### ISSUE THREAD

**Issue by atulkc** [pivotal-cf/cf-rabbitmq-release#21]
We are trying to configure rabbitmq to use two way tls for authenticating users using bosh. However, when we specify the configuration to `verify, verify_peer` and `fail_if_no_peer_cert, true` as part of bosh deployment manifest it does not take effect.

Further investigation revealed that following line in setup.sh is actually specifying `verify, verify_none` and `fail_if_no_peer_cert, false`
https://github.com/pivotal-cf/cf-rabbitmq-release/blob/master/jobs/rabbitmq-server/templates/setup.sh.erb#L140

This setting is taking effect instead of the settings specified in the bosh deployment manifest for bosh-lite
```
config: <%= ["[{rabbit,[{auth_mechanisms, ['EXTERNAL']},{auth_backends, [rabbit_auth_backend_internal]}, {ssl_listeners, [5671]}, {ssl_options, [{cacertfile,\"/var/vcap/jobs/rabbitmq-server/bin/../etc/cacert.pem\"},{certfile,\"/var/vcap/jobs/rabbitmq-server/bin/../etc/cert.pem\"},{keyfile,\"/var/vcap/jobs/rabbitmq-server/bin/../etc/key.pem\"},{verify,verify_peer},{fail_if_no_peer_cert,true},{versions,['tlsv1.2','tlsv1.1',tlsv1]}]}]},{rabbitmq_mqtt,[{allow_anonymous, false},{ssl_listeners, [8883]},{ssl_cert_login, true}]}]."].pack("m0") %>
```
Is this causing our configuration not to be honored? How can we get rabbitmq enforce two way TLS with bosh? May be providing bosh deployment manifest properties to configure these options and using them in `setup.sh.erb` will help?

**Comment by svett** [comment]
The both properties are exposed in the job spec. I am closing the issue.
