### ISSUE TITLE
Can we set a cluster name using a deployment manifest?

### ISSUE THREAD

**Issue by kinjelom** [pivotal-cf/cf-rabbitmq-release#270]
Now (v3.8) the cluster name is exported by [`prometheus_exporter` as `rabbitmq_identity_info.rabbitmq_cluster`](https://github.com/rabbitmq/rabbitmq-prometheus/blob/master/src/collectors/prometheus_rabbitmq_core_metrics_collector.erl#L262).

By default the cluster name is `root@localhost` and can be changed using "Management UI".

Is it a good idea to set it using a deployment manifest?

For example [`/jobs/rabbitmq-server/templates/post-deploy.bash`](https://github.com/pivotal-cf/cf-rabbitmq-release/blob/master/jobs/rabbitmq-server/templates/post-deploy.bash):
```erb
<% if_p("rabbitmq-server.cluster.name") do |cluster_name| %>
  rabbitmqctl set_cluster_name <%= cluster_name %>
<% else %>
  rabbitmqctl set_cluster_name <%= spec.deployment %>.bosh
<% end %>
```
- https://www.rabbitmq.com/rabbitmqctl.8.html#set_cluster_name
- https://bosh.io/docs/jobs/#properties-spec

**Comment by ansd** [comment]
Hi @kinjelom,
yes, that's indeed a good idea.
We did what you requested in https://github.com/pivotal-cf/cf-rabbitmq-release/commit/c43dd992f5abc0a56c4ae1d6f1a566296ec8ac68.
