### ISSUE TITLE
Installing Additional Plugins with RMQ Bosh release

### ISSUE THREAD

**Issue by Infra-Red** [pivotal-cf/cf-rabbitmq-release#28]
Hi!
At current moment i have a need to add some additional community plugins to existing RabbitMQ BOSH installation. Is there any simple way to add external plugins without reworking existing release and switching on develop version?
Thanks!

**Comment by davidhiston** [comment]
Hi.  We have no intentions of supporting the community plugins in the short term.  We suggest that you create your own bosh release which includes a package which contains the community plugins.  Then you can define a job to copy these plugins into the rabbitmq plugins directory.  You can then then co-locate the job with the existing within the existing rabbitmq release, and run the job for every rabbitmq node.
Thanks.
