### ISSUE TITLE
rmq_tracing plugin is not working and gives a 500 error.

### ISSUE THREAD

**Issue by GuruprakashS** [pivotal-cf/cf-rabbitmq-release#29]
Hi Team, we have enabled 'rabbitmq_tracing' plugin in Pivotal RabbitMQ release version: 210.8.0.  
We are able to see the tracing tab enabled in the administrator console however while we click on it, it gives a 500 Error with the error description as below. Request your help here.

Error trace::
webmachine error: path="/api/trace-files"
{error,{error,{badmatch,{error,eacces}},
             [{rabbit_tracing_files,list,0,[]},
              {rabbit_tracing_wm_files,to_json,2,[]},
              {webmachine_resource,resource_call,3,[]},
              {webmachine_resource,do,3,[]},
              {webmachine_decision_core,resource_call,1,[]},
              {webmachine_decision_core,decision,1,[]},
              {webmachine_decision_core,handle_request,2,[]},
              {rabbit_webmachine,'-makeloop/1-fun-0-',2,[]}]}}

Thanks,
Guru.

**Comment by GuruprakashS** [comment]
This is a RMQ clustering setup with 2 RMQ nodes.

**Comment by michaelklishin** [comment]
That plugin writes files to a local file system and in your case encounters an `EACCESS`.

**Comment by michaelklishin** [comment]
Since rabbitmq-tracing is nothing more than a trivial consumers and logger/UI for [RabbitMQ firehose](http://www.rabbitmq.com/firehose.html), I'd question its usefulness in environments such as PCF. Use a small app that consumes traces and is deployed to CF instead.

**Comment by michaelklishin** [comment]
Lastly, `rabbitmq_tracing.directory` can be used to override trace logs directory location.

**Comment by GuruprakashS** [comment]
Hey Mike, thanks for taking a look.

Yes, we are trying to debug an issue with p. RMq and hence we want to enable tracing temporarily.
Is there a way at all to enable tracing. For now all we did was enabled rabbit_tracing property under the plugins section. Should there be any other properties added under jobs for the tracing plugins to work.

I'd appreciate if you give us pointers or share a sample manifest. We don't want to take the sample app route to capture trace at this point of time and would want to leverage enabling the plugins through bosh release.

Thanks

**Comment by michaelklishin** [comment]
@GuruprakashS please see the comments above.

**Comment by GuruprakashS** [comment]
@michaelklishin : Thanks for the pointer. Based on your comment we thought `rabbitmq_tracing.directory` to be a property under properties section of rmq-server section. But later we figured out that the following section in the manifest is to be added for the tracing plugin to work.

```
properties:
    rabbitmq-server:
    config: <%= ["[{rabbitmq_tracing, [{directory, "/my/log/file/location"},{username,  "guest"}]}]. "]%>
```
