### ISSUE TITLE
How to run custom `rabbitmqctl` commands post start RabbitMQ server?

### ISSUE THREAD

**Issue by kinjelom** [pivotal-cf/cf-rabbitmq-release#332]
I want to enable the `rabbitmq_tracing` plugin:
```
- type: replace
  path: /instance_groups/name=rmq/jobs/name=rabbitmq-server/properties/rabbitmq-server/plugins/-
  value: rabbitmq_tracing
```
and make it ready to produce events: `rabbitmqctl  trace_on -p my-vhost`

How to run it `post-start` RabbitMQ server?
Is there a place in the deployment manifest where I can put commands required to get plugin working?

**Comment by kinjelom** [comment]
What about `cf-rabbitmq-release/jobs/rabbitmq-server/templates/post-start.bash`:
```
run_rabbitmqctl_cmds() {
  write_log "Running rabbitmqctl commands..."
  <% p("rabbitmq-server.post_start_rabbitmqctl_cmds").each do |cmd| %>
    write_log "- <%= cmd %> ..."
    cmd_out=$(${RMQ_CTL} <%= cmd %>)
    write_log "output: ${cmd_out}"
  <% end %>
}
```
and ops:
```
- type: replace
  path: /instance_groups/name=rmq/jobs/name=rabbitmq-server/properties/rabbitmq-server/post_start_rabbitmqctl_cmds?/-
  value: "trace_on -p  my-vhost"
```

**Comment by MirahImage** [comment]
While the suggested templating would work in companion with a corresponding re-architecting of the `spec.properties` and deployment manifests to allow customization of post-start scripts, this would introduce significant breaking changes for all users.

Furthermore, enabling tracing is not a common use case, especially in production environments.

We should note that it is possible to enable the plugin manually, though this will be overridden on the next bosh deployment.
