### ISSUE TITLE
cf-rabbitmq.yml has test configurations

### ISSUE THREAD

**Issue by Omnipresent** [pivotal-cf/cf-rabbitmq-release#37]
https://github.com/pivotal-cf/cf-rabbitmq-release/issues/36 is related to this issue

the `cf-rabbitmq-yml` manifests seems to have settings that the team is using for testing purposes. This breaks running `scripts/deploy-bosh-lite` for end users trying to deploy cf-rabbitmq on their instances of bosh-lite

**Comment by Omnipresent** [comment]
Bump. Just wondering if there is any update on this.

**Comment by vlad-stoian** [comment]
Closing based on resolving [this](https://github.com/pivotal-cf/cf-rabbitmq-release/pull/41#issuecomment-318108481)
