### ISSUE TITLE
broker registrar error

### ISSUE THREAD

**Issue by cpraveen412** [pivotal-cf/cf-rabbitmq-release#39]
Hi team!!
I'm installing rabbitmq on vsphere using the below deployment manifest.

https://gist.github.com/cpraveen412/fc724dccd4338e9dc771b3b5597e2e10

deployment was successful but getting error while i was runnung errand command
bosh run errand broker-registrar

below are the errors

![image](https://cloud.githubusercontent.com/assets/19999722/20185115/e0c2c3e4-a738-11e6-948a-6a1f378dfffc.png)

![image](https://cloud.githubusercontent.com/assets/19999722/20185159/023c68ae-a739-11e6-898f-0306c162ac0a.png)

**My Environment**
vsphere vcenter (with single datacenter, single cluster and only one node in that cluster)
bosh stemcell v3263.7
cf v245
rabbitmq v224.0.0

**Comment by gerhard** [comment]
@cpraveen412 [Lines 121 & 122](https://gist.github.com/cpraveen412/fc724dccd4338e9dc771b3b5597e2e10#file-cf-rabbitmq-deployment-yml-L121-L122) in your manifest are used to authenticate to CF when registering the broker. Are those credentials correct?
