### ISSUE TITLE
update-release not working

### ISSUE THREAD

**Issue by cpraveen412** [pivotal-cf/cf-rabbitmq-release#40]
Hi Team!!
I'm getting the following message while i was updating the release using ./scripts/update-release command

The agent has no identities.
Please add your ssh key

Can anyone help me?

Thanks In Advance

**Comment by michaelklishin** [comment]
That's is next to no information to work with. Please at least post a terminal session transcript that demonstrates what you do and what the full error is.

**Comment by cpraveen412** [comment]
Hi @michaelklishin 
Thank you for your response. Even i have no clue what to with these lines. after observing the script, i realised that the command ssh-add -l did not find any keys to bind. so working on it.

**Comment by cpraveen412** [comment]
Got it.
Followed this procedure to solve it

https://help.github.com/articles/generating-an-ssh-key/
