### ISSUE TITLE
Why is max_in_flight = 4 in templates?

### ISSUE THREAD

**Issue by MatthiasWinzeler** [pivotal-cf/cf-rabbitmq-release#44]
We noticed that `max_in_flight` is set to `4` in the [deployment templates](https://github.com/pivotal-cf/cf-rabbitmq-release/blob/ba16c6adfc57ca89e951ee5a04af428133ca35f7/templates/cf-rabbitmq-deployment.yml#L182).

We're running our RMQ clusters with 3 nodes. 
With max_in_flight = 4, it will update the remaining 2 nodes simultaneously after the canary. Thus, *all* HA queues will be moved to a single node (the canary) which we think is not optimal. 

Is there a specific reason why you set max_in_flight to 4 or can we safely reduce this to 1?

**Comment by davidhiston** [comment]
Hi Matthias, 

You may safely set this to one and we shall update the deployment manifests to change it to one. 

Thanks, 

Dave

**Comment by MatthiasWinzeler** [comment]
Thanks for the explanation, we'll set it to one.
