### ISSUE TITLE
Cluster config with hostnames vs. IP addresses

### ISSUE THREAD

**Issue by eLobeto** [pivotal-cf/cf-rabbitmq-release#47]
Currently to set up clustered Rabbit nodes, the IP's of all the nodes need to be passed in via the manifest. I attempted to set up clustering by passing in hostnames which will always be the same, but the Rabbit jobs kept failing. Is there a property to set to allow hostnames instead of IP's or a way to tweak the scripts to accommodate this?

Thanks!

**Comment by davidhiston** [comment]
Hi, 

Currently we require that you supply IP addresses, as we don't currently support resolving hostnames in our release for CF.  This is not planned for the near term and so I will close this issue. 

Thanks, 

Dave
