### ISSUE TITLE
Since 2021-02-24, `disk_alarm_threshold` does not accept integer values anymore

### ISSUE THREAD

**Issue by bgandon** [pivotal-cf/cf-rabbitmq-release#472]
Hi Connor (@coro),

In your commit `bd07ab63` dated 2021-02-24, you have implement [some restrictive regexp validation](https://github.com/pivotal-cf/cf-rabbitmq-release/commit/bd07ab639fe9b8ddede965136425e16250bff8e5#diff-45634a0ed17f9f34f16ce059b7c824e50f830d2a051bfcf5f39985b1c5fd525dR24) to the `rabbitmq-server.disk_alarm_threshold` property of the `rabbitmq-server` job.

The problem is that Integers were properly supported for this setting before (as advertised [in the job's spec](https://github.com/pivotal-cf/cf-rabbitmq-release/blob/bd07ab639f/jobs/rabbitmq-server/spec#L90)), and aren't anymore. [Line 24](https://github.com/pivotal-cf/cf-rabbitmq-release/blob/bd07ab639f/jobs/rabbitmq-server/templates/config-files/10-clusterDefaults.conf.erb#L24) of the new `10-clusterDefaults.conf.erb` file, [the `threshold.match` invocation](https://github.com/pivotal-cf/cf-rabbitmq-release/blob/bd07ab639f/jobs/rabbitmq-server/templates/config-files/10-clusterDefaults.conf.erb#L24) will break if `threshold` is an integer.

I know `mem_relative` is recommended in the Pivotal Tile, but in BOSH-Lite environments at our company, we don't want to specify this threshold as a relative percentage of the total RAM, because we don't wan't this settings to depend on what amount of RAM has actually been allocated to the overall to BOSH-Lite environment.

Could you please update this ERB file in order to accept integer values for `rabbitmq-server.disk_alarm_threshold`? Thanks!

Best

**Comment by bgandon** [comment]
Any news on this?

**Comment by Zerpet** [comment]
Hi @bgandon, this went under our radar, I'll bring it up to the team.

**Comment by coro** [comment]
Hello @bgandon , apologies for missing this and thanks to @Zerpet for bringing it up. Could you give me an example of a value of this field that no longer works? The commit was intended to be backwards compatible, i.e. if you previously provided a value that doesn't match the `mem_relative` regex like `500Mi`, it would be applied to the config as `disk_free_limit.absolute - 500Mi`. In your case, an integer should be mapped to this absolute value, as in the example configs at https://www.rabbitmq.com/disk-alarms.html#configure.

**Comment by coro** [comment]
In case that's not clear - here is a unit test demonstrating what I mean. If you were specifying just an integer here, it should be mapped to `disk_free_limit.absolute`.

https://github.com/pivotal-cf/cf-rabbitmq-release/blob/3a4aab87796ef9d2fc98415a521f5936c5246783/spec/unit/templates/10-clusterDefaults_spec.rb#L67-L77

**Comment by coro** [comment]
I'm closing this issue as it's been stale a while. Please let us know if the snippet above doesn't help you.
