### ISSUE TITLE
Compile Erlang consistently with other RabbitMQ releases

### ISSUE THREAD

**Issue by coro** [pivotal-cf/cf-rabbitmq-release#499]
In this BOSH release, Erlang is configured/compiled with mostly Erlang-default settings, with the only modification being the addition of the latest OpenSSL version, so that we are not reliant on the underlying stemcell OS's openssl version & can guarantee we're using the latest cipher suites & support for TLS1.3.

In the container-based distributions of RabbitMQ, we configure Erlang/OTP with optimisations in place to remove unused libraries, etc. I have merged the configuration options we use there into the BOSH release packaging script below, with notes on which flags are not currently used here, but are in container-land:

```bash
./configure \
  --with-ssl="/var/vcap/packages/openssl/external/openssl/" \
  --with-ssl-rpath="/var/vcap/packages/openssl/external/openssl/lib/" \
# -------------- vvv Included in RabbitMQ Dockerfile vvv -------------
	--disable-hipe \ # not even shipped in erl24 - don't know if it does anything anymore
	--disable-sctp \ # unused in RabbitMQ
	--disable-silent-rules \ # less verbose build output
	--enable-clock-gettime \ # Use clock-gettime for time correction - can't find any docs explaining this, and it's not in the output of ./configure --help
	--enable-hybrid-heap \ # Each process has a private heap, but a shared heap is used for messages. Not in the output of ./configure --help. I've seen a paper concluding that this kind of heap may be preferrable - https://user.it.uu.se/~kostis/Papers/heap.pdf
	--enable-kernel-poll \ # Already enabled by default anyway
	--enable-shared-openssl \ # I think this is incompatible with us using our own openssl, so we shouldn't enable this. Not in the output of ./configure --help.
	--enable-shared-zlib \ # Shared zlib library. Can't find out the implications of that. Not in the output of ./configure --help.
	--enable-smp-support \ # Symmetric Multi Processing. Already enabled by default if available. Not in the output of ./configure --help.
	--enable-threads \ # Not in the output of ./configure --help.
	--prefix=${OTP_INSTALL_DIR} \ # already set below
	--with-microstate-accounting=extra \ # Adds extra output to rabbitmq-diagnostics runtime_thread_stats to see where schedulers are spending their time. Minimal perf impact, but very useful for diagnosing deep issues.
	--without-common_test \ # These are all 'do not compile with this package'. Since they're not used in Tanzu/OSS RMQ images, we can do without them here. Omitting them *I believe* will reduce compile/install time, but I'm not sure.
	--without-debugger \
	--without-dialyzer \
	--without-diameter \
	--without-edoc \
	--without-erl_docgen \
	--without-et \
	--without-eunit \
	--without-ftp \
	--without-hipe \ # not even shipped in erl24
	--without-jinterface \
	--without-megaco \
	--without-observer \
	--without-odbc \
	--without-reltool \
	--without-ssh \
	--without-tftp \
	--without-wx \
# -------------- ^^^ Included in RabbitMQ Dockerfile ^^^ -------------
  --prefix=${BOSH_INSTALL_TARGET}
```

I haven't been able to find out the impact of some of these flags, so I invite comment to help me work out which should be enabled here on BOSH infrastructure. We may find that some of these flags aren't needed anywhere. @gerhard @dumbbell @essen

**Comment by gerhard** [comment]
`--enable-shared-openssl` should be dropped if we are compiling OpenSSL, and also use `--disable-dynamic-ssl-lib`. Everything else looks correct to me. I would also add the `--enable-lock-counter` option: https://erlang.org/doc/apps/tools/lcnt_chapter.html

References:
- https://github.com/docker-library/rabbitmq/blob/master/3.9/ubuntu/Dockerfile#L134-L163
- https://github.com/rabbitmq/tanzu/blob/2b659521ecd2e201ecf30260e04a5a8e699c2cb7/1.0.0/docker/otp/Dockerfile#L58-L89 (not public)

**Comment by dumbbell** [comment]
I don't know if this Erlang copy is used to compile RabbitMQ, but I personally like to use eunit assertions in my code. Those are macros, so the eunit applications is only useful at compile time, not runtime. With `--without-eunit`, RabbitMQ won't compile.

Erlang uses sub-configures. You will find that many of the flags are defined in `erts/configure.ac`. You can thus run `./erts/configure --help` to get more descriptions.

**Comment by gerhard** [comment]
This is only used to run RabbitMQ, and should not be used to compile RabbitMQ.

For compiling RabbitMQ we should **only** use these dedicated images: https://hub.docker.com/r/pivotalrabbitmq/rabbitmq-server-buildenv

**Comment by coro** [comment]
I've just implemented these changes in the linked PR. @gerhard I tried your recommendations, however I found I had to include both `--enable-dynamic-ssl` and `--enable-dynamic-ssl-lib` in order to succeed when using `--with-ssl-rpath`; see lines 5946-5973 in https://fossies.org/linux/otp/lib/crypto/configure
