### ISSUE TITLE
error generating manifest: unresolved nodes in v225.0.0

### ISSUE THREAD

**Issue by eujungkim** [pivotal-cf/cf-rabbitmq-release#53]
When I ran "./scripts/generate-manifest openstack" in v225.0.0 with no modification, 
the error occurred like below.

2017/04/24 09:16:17 error generating manifest: unresolved nodes:
        (( merge ))     in /service-v3/cf-rabbitmq-release/templates/cf-rabbitmq-infrastructure-openstack.yml  networks        (networks)

**Comment by BenChapman** [comment]
Hi,

As a result of using BOSH Links and the new BOSH CLI v2, we've changed the way we generate manifests. As a result the old spiff way is no longer supported.

You can find instructions on how to generate a manifest in [our readme](https://github.com/pivotal-cf/cf-rabbitmq-release/blob/master/README.md).

@BenChapman & @dlresende
