### ISSUE TITLE
The deploy-bosh-lite script still contains BOSH v1 cli instruction word in v225.

### ISSUE THREAD

**Issue by eujungkim** [pivotal-cf/cf-rabbitmq-release#54]
I think v225 release is made for using BOSH v2.

But the "scripts/deploy-bosh-lite" file still contains BOSH v1 cli instruction words.

For example, 
 - bosh target
 - bosh upload release
 - ...

**Comment by BenChapman** [comment]
Hi,

Thanks for your issue. We've since changed all of our scripts and repos to use the new BOSH CLI v2.

@benchapman & @dlresende
