### ISSUE TITLE
Rabbitmq-server Job Spec or setup.sh.rb

### ISSUE THREAD

**Issue by stu-pete** [pivotal-cf/cf-rabbitmq-release#55]
We found this in Pivotal CloudFoundry when upgrading the Rabbit Tile:

SPEC File:

> rabbitmq-server.disk_alarm_threshold:
   > description: "The threshold in bytes of free disk space at which rabbitmq will raise an alarm"
    > default: "{mem_relative,0.4}"

setup.sh.erb

> SERVER_START_ARGS="SERVER_START_ARGS='-rabbitmq_clusterer config \"${CLUSTER_CONFIG}\" >-rabbit log_levels [{connection,info}] -rabbit disk_free_limit <%= disk_alarm_threshold %> -rabbit >cluster_partition_handling <%= cluster_partition_handling %> -rabbit halt_on_upgrade_failure false >-rabbitmq_mqtt subscription_ttl 1800000"

It should either be **"[{mem_relative,0.4}]"**  in the spec file or the injection into setup.sh.erb should be **[<%= cluster_partition_handling %>]**

It probably passed tests because monit does not realize that the startup of the job actually errors out with:

> BOOT FAILED
> ===========

>Error description:
>{could_not_start,rabbit,
>{error,
>{{shutdown,
>{failed_to_start_child,rabbit_memory_monitor,
>{badarg,
>[{lists,member,[disk,{error,bad_module}],[]},
>{rabbit_memory_monitor,init,1,
>[{file,"src/rabbit_memory_monitor.erl"},
>{line,121}]},
>{gen_server2,init_it,6,
>[{file,"src/gen_server2.erl"},{line,554}]},
>{proc_lib,init_p_do_apply,3,
>[{file,"proc_lib.erl"},{line,247}]}]}}},
>{child,undefined,rabbit_memory_monitor_sup,
>{rabbit_restartable_sup,start_link,
>[rabbit_memory_monitor_sup,
>{rabbit_memory_monitor,start_link,[]},
>false]},
>transient,infinity,supervisor,
>[rabbit_restartable_sup]}}}}

**Comment by gerhard** [comment]
@stu-pete `[{mem_relative,0.4}]` is incorrect, I have confirmed that it does not work in RabbitMQ 3.6.9. As a matter of fact, it shouldn't work in any RabbitMQ version.

The error that you're describing is what I would expect to see when you have less disk space available than the disk_free_limit value. For example, if your disk is 10GB and your memory is 32GB, `{mem_relative,0.4}` would be 12.8GB which is more than 10GB. I have also confirmed this behaviour in RabbitMQ 3.6.9.

cc @dumbbell @scottmuc

**Comment by stu-pete** [comment]
@gerhard
Why is log_levels passed this way?
-rabbit log_levels [{connection,info}]

**Comment by gerhard** [comment]
Some configuration values require a list, as is the case of `log_levels`, and some commands work with either integers or tuples, as is the case of `disk_free_limist`. You can find more on the [official RabbitMQ configuration page](http://www.rabbitmq.com/configure.html).

This is a valid rabbitmq.config:

```erl
[
    {rabbit,
        [
            {disk_free_limit, {mem_relative, 1.0}}
        ]
    }
].
```

This is not a valid rabbitmq.config:

```erl
[
    {rabbit,
        [
            {disk_free_limit, [{mem_relative, 1.0}]}
        ]
    }
].
```

This is a valid erl argument:

```sh
erl ... \
  -rabbit disk_free_limit {mem_relative,1.0}
```

This is not a valid erl argument:

```sh
erl ... \
  -rabbit disk_free_limit [{mem_relative,1.0}]
```

RabbitMQ will start and appear to run, but it won't work properly as different processes will crash and be restarted inside the Erlang VM.

Can you please tell me how much memory does your host running RabbitMQ have and how much disk space does the mount used for `RABBITMQ_MNESIA_BASE` have (I suspect this to be  `/var/vcap/store/rabbitmq`)?

**Comment by stu-pete** [comment]
I'm sorry, you were completely right with disk/ram issue. Once we changed VM disk size the job does not throw bad argument error.
df -h:
/dev/vdc1        30G   48M   28G   1% /var/vcap/store
free -g:
Mem:            31          0         30          0          0          0

**Comment by gerhard** [comment]
Glad we could fix the issue 👍
