### ISSUE TITLE
New bosh links doesn't seem to work with previous manifest

### ISSUE THREAD

**Issue by peterellisjones** [pivotal-cf/cf-rabbitmq-release#554]
Hi folks,

The latest [release 418](https://github.com/pivotal-cf/cf-rabbitmq-release/releases/tag/v418.0.0) introduced a new bosh link consumed by the rabbitmq-server job in PR #550. 

Unfortunately this change causes our deployment to break with:

```
Task 6116 | 01:51:55 | Error: Failed to resolve links from deployment 'rabbitmq'. See errors below:

  - Failed to resolve link 'rabbitmq-server-dns-name' with type 'address' from job 'rabbitmq-server' in instance group 'rmq'. Details below:

    - No link providers found
```

The PR adds a 'consumes' section in the `rabbitmq-server` job spec https://github.com/pivotal-cf/cf-rabbitmq-release/blob/8ffdff7a40b5a534bfd2d5c7fec947822db48b60/jobs/rabbitmq-server/spec#L208-L209 but does not seem to any corresponding link providers which is required to create a complete bosh link "consumes-provides" pair.

**Comment by peterellisjones** [comment]
Update: 

we were able to fix this with 

```
provides:
   rabbitmq-server-dns-name: { as: rabbitmq-server }
```

In the `rabbitmq-server` configuration

**Comment by ablease** [comment]
Hi @peterellisjones Thanks for noticing this, and apologies for breaking your deployment. 

With this commit https://github.com/pivotal-cf/cf-rabbitmq-release/commit/d162c17e0718fed99bf7ab40708249d88fa334dc, we are providing the link in the rabbitmq-server job.
