### ISSUE TITLE
rabbitmqadmin not found

### ISSUE THREAD

**Issue by eujungkim** [pivotal-cf/cf-rabbitmq-release#58]
I deployed cf-rabbitmq-release v226.0.0.
I included "rabbitmq_management" to plugins.
When I browsed to http://pivotal-rabbitmq.[MY_DOMAIN]/cli, it displayed like below.

**rabbitmqadmin**
Download it from here (Right click, Save as), make executable, and drop it in your path.

But when I click "here" to download rabbitmqadmin, the response was {"error":"Object Not Found","reason":"Not Found"} and I failed to get rabbitmqadmin.

**Comment by michaelklishin** [comment]
I suspect that CF router only has routes for `/api` (the actual API).

`rabbitmqadmin` is a no-dependency Python script, so you can [download it directly from GitHub](https://github.com/rabbitmq/rabbitmq-management/blob/stable/bin/rabbitmqadmin).

**Comment by eujungkim** [comment]
Thank you for your kind answer.
