### ISSUE TITLE
Location of RABBITMQ_MNESIA_BASE

### ISSUE THREAD

**Issue by johnmcteague** [pivotal-cf/cf-rabbitmq-release#6]
The RABBITQM_MNESIA_BASE and _DIR directories are on /var/vcap/store rather than the persistent volume /var/vcap/data. Our openstack stemcells only have a 3GB root partition so they can fill up fairly quickly.

Is there a reason it doesnt use the volume? What is the volume on rabbit-server for?

**Comment by michaelklishin** [comment]
No particular reason. Back when the project was started, there wasn't a terrible lot of BOSH documentation available.

If `/var/vcap/store` is not supposed to be used by data services, we should migrate to `/var/vcap/data`.

**Comment by johnmcteague** [comment]
Been an idiot, sorry. I managed to deploy without a persistent disk.
