### ISSUE TITLE
Unusual variable names

### ISSUE THREAD

**Issue by sambryant4** [pivotal-cf/cf-rabbitmq-release#62]
There are a number of instances in the base manifests that have some quite unusual variable names, an example being:
```
management_domain: ((rabbitmq-management-domain)).((bosh-hostname))
```
or
```
uris:
   - ((rabbitmq-broker-domain)).((bosh-hostname))
```
Considering a uri would normally be considered `<hostname>.<domain>` this becomes quite confusing.

**Comment by BenChapman** [comment]
Hi @sambryant4,

Thanks for the suggestion. We've now renamed rabbitmq-X-domain to rabbitmq-X-hostname, and changed bosh-hostname to bosh-domain.

Thanks,
@benchapman & @dlresende
