### ISSUE TITLE
Difference between branches / bosh.io

### ISSUE THREAD

**Issue by MatthiasWinzeler** [pivotal-cf/cf-rabbitmq-release#64]
Hi guys

If I check the [releases](https://github.com/pivotal-cf/cf-rabbitmq-release/releases), there are three different branches maintained:
- master (v231, v232, ...)
- v226.x
- v222.x

We were wondering: What's the difference between them? Is there some doc about it?

We also noticed that only the artifacts based on master are published on bosh.io.
Is there a reason for this?

**Comment by BenChapman** [comment]
Hi @MatthiasWinzeler,

Thanks for your question. We now only actively develop on master, and have a branch for each new final (which are always major version numbers). We have previously maintained specific "old" branches for external dependencies on those branches. We now recommend using the latest tagged version (from Bosh.io) for general use.

@benchapman & @dlresende
