### ISSUE TITLE
How can I set the 'Memory Threshold'?

### ISSUE THREAD

**Issue by mymasse** [pivotal-cf/cf-rabbitmq-release#66]
So we've hit the memory threshold on one of our rabbit-server node today. Looking at the configuration found this: 

`[{rabbit, [{vm_memory_high_watermark, 0.4}]}].`

How can we change this 40% limit. 40% seems quite low on my bosh managed vm, I looked at the bosh vitals when the alarm was triggered and I was only using 51% of current RAM. Seems like using 40% is wasting a lot of memory.

Can't find anywhere I can update this value.

**Comment by dlresende** [comment]
Hi @mymasse,

As of today you cannot change the `vm_memory_high_watermark` using this BOSH release.

Today one can only change [the disk alarm](https://github.com/pivotal-cf/cf-rabbitmq-release/blob/master/jobs/rabbitmq-server/spec#L57-L59).

@henderjm & Diego
