### ISSUE TITLE
the difference between the latest version and v215.0.0

### ISSUE THREAD

**Issue by raniatriki** [pivotal-cf/cf-rabbitmq-release#67]
Hello, 

Please!! 
Can anyone help me on the difference between version 215.0.0 and the latest version? 
For example  the cf-rabbitmq-template file : instance groups, propreties ...

Thank you

**Comment by raniatriki** [comment]
Please, how do you update the manifests of each release!!!

**Comment by henderjm** [comment]
This not an issue.
