### ISSUE TITLE
Repo no longer contains a service-broker?

### ISSUE THREAD

**Issue by wbean1** [pivotal-cf/cf-rabbitmq-release#79]
We've been using the `v226` branch of this repo, and at that point the release contained a `rabbitmq-broker` job and `broker-registrar` / `broker-deregistrar` errands.  It looks like this repo no longer contains those things, and they are now separated to https://github.com/pivotal-cf/cf-rabbitmq-multitenant-broker-release ? Is that accurate?

So is the idea you use this to deploy your rabbitmq server infrastructure, then deploy the "multitenant-broker" separately pointing it at this server infrastructure?

All of this is very unclear from supplied README documentation, Release Notes, and previous issues.  It would be nice if changes to the structure of the release and its intended usage were documented somewhere.  Maybe it is and I just don't know where to look?

**Comment by albertoleal** [comment]
Hi @wbean1 , yes you’re right. We have split both releases into two different repositories, but that doesn’t mean you cannot have both colocated in the same VM.

We’re using a collection of ops-files and vars-files, features from Bosh 2, to generate manifests. You’ll find a folder called “manifests” in both repos with a manifest template and some ops-files and example of vars-files. You should be able to create and collocate both releases leveraging the ops-file in the multitenant broker repo: https://github.com/pivotal-cf/cf-rabbitmq-multitenant-broker-release/blob/master/manifests/add-cf-rabbitmq.yml

More information about bosh interpolate here: https://bosh.io/docs/cli-int/

Sorry about the confusion. I hope this helps you out. I’ll make sure we have this information in our Readme along with some examples as well. I appreciate your feedback on that. 

Cheers,
Alberto

**Comment by wbean1** [comment]
Thanks for the quick response & helpful information, @albertoleal.  The link to the example ops-file in the broker repo is exactly the missing puzzle piece I was looking for.

**Comment by albertoleal** [comment]
Great! I'm closing this issue then. Let us know how in case you need anything else.
