### ISSUE TITLE
RabbitMq console management url won't work when https enabled

### ISSUE THREAD

**Issue by datianshi** [pivotal-cf/cf-rabbitmq-release#8]
When https enabled, the Rabbit Management console node is only https based. E.g. https://[ip]:15762, while the proxy is also https based forwarding.

However the route registered with router won't work (time out error). pivotal-rabbitmq.10.244.0.34.xip.io
Because router -> Rabbit Proxy is only http based

Shaozhen Ding
Pivotal Services

**Comment by cghsystems** [comment]
Hi 

We have a story in Tracker to tackle the issue. Please see https://www.pivotaltracker.com/story/show/91944784 for more information.

If you require Tracker access to follow the story please let us know.

Thanks

Chris and Tiago

**Comment by benlaplanche** [comment]
Hi @datianshi i'm closing this issue as this was resolved in the latest releases and version of the RabbiMQ tile 1.4.1
